# Generated by Django 4.1.2 on 2022-11-19 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommender",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
                ("current_points", models.PositiveIntegerField(default=0)),
                ("credibility", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommender",
                "verbose_name_plural": "Recommenders",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("confirmed", "Confirmed")],
                        default="invited",
                        max_length=30,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommenders.recommender",
                    ),
                ),
            ],
        ),
    ]
