# Generated by Django 4.1.2 on 2022-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("invited", "Invited"), ("confirmed", "Confirmed")],
                        default="invited",
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
