# Generated by Django 4.1.2 on 2022-10-29 16:04

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("recommenders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommender",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
                ("current_points", models.PositiveIntegerField(default=0)),
                ("credibility", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommender",
                "verbose_name_plural": "Recommenders",
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="referrer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recommenders.recommender",
            ),
        ),
    ]
