# Generated by Django 4.1.2 on 2022-11-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommenders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommender",
            name="address",
        ),
    ]
