# Generated by Django 4.1.2 on 2022-10-29 16:14

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("recommenders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="recommender",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
