# Generated by Django 4.1.2 on 2023-01-25 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
        ("candidates", "0002_candidate_advertisement_candidate_advertisement_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="advertisement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidate_advertisement",
                to="advertisements.advertisement",
                verbose_name="advertisement",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="advertisement_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Advertisement"
            ),
        ),
    ]
