# Generated by Django 4.1.2 on 2023-01-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_alter_candidate_advertisement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("invited", "Invited"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="invited",
                max_length=30,
            ),
        ),
    ]
