# Generated by Django 4.1.2 on 2023-01-13 23:20

import django.db.models.deletion
from django.db import migrations, models

import shop.models
import shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(
                help_text="First image will be displayed as reward's main image in shop.",
                upload_to=shop.models.upload_to_rewards,
                validators=[shop.utils.validate_file_extension],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_images",
                to="shop.reward",
                verbose_name="reward",
            ),
        ),
    ]
