# Generated by Django 4.1.2 on 2023-01-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommender",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("current_points", models.PositiveIntegerField(default=0)),
                ("credibility", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommender",
                "verbose_name_plural": "Recommenders",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
