# Generated by Django 4.1.2 on 2022-11-06 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("company", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "CompanyAdmin",
                "verbose_name_plural": "CompanyAdmins",
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
