# Generated by Django 4.1.2 on 2023-01-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_alter_candidate_advertisement_and_more"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Advertisement",
        ),
    ]
