# Generated by Django 4.1.2 on 2022-11-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyadmin",
            options={
                "verbose_name": "Company Admin",
                "verbose_name_plural": "Company Admins",
            },
        ),
    ]
