# Generated by Django 4.1.2 on 2022-11-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("COMMERCIAL", "Commercial"),
                            ("RECRUITMENT", "Recruitment"),
                        ],
                        max_length=11,
                    ),
                ),
                ("reward_for_approval", models.PositiveIntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.companyadmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisment",
                "verbose_name_plural": "Advertisments",
            },
        ),
    ]
