# Generated by Django 4.1.2 on 2023-01-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_alter_companyadmin_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Advertisment",
            new_name="Advertisement",
        ),
        migrations.AlterModelOptions(
            name="advertisement",
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
            },
        ),
    ]
