# Generated by Django 4.1.2 on 2022-11-06 13:29

import django.db.models.deletion
from django.db import migrations, models

import shop.models
import shop.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("cost", models.PositiveIntegerField()),
                ("short_description", models.TextField(max_length=300)),
                ("long_description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("PHYSICAL", "Physical"), ("DIGITAL", "Digital")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=shop.models.upload_to_rewards,
                        validators=[shop.utils.validate_file_extension],
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.reward"
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
