# Generated by Django 4.1.2 on 2022-10-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=50)),
                ("l_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("passwd", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("current_points", models.IntegerField()),
                ("credibility", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
