# Generated by Django 4.1.2 on 2022-10-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_candidate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommender",
            options={
                "verbose_name": "Recommender",
                "verbose_name_plural": "Recommenders",
            },
        ),
    ]
